name: Spring Boot CI/CD Pipeline

# This workflow is triggered on push and pull request events to the specified branches
on:
  push:
    branches: [main, develop, "feature/**", "release/**"]
  pull_request:
    branches: [main, develop, "release/**"]

# Environment variables that can be used throughout the workflow
env:
  JAVA_VERSION: "17"
  MAVEN_VERSION: "3.9.6"
  SPRING_PROFILES_ACTIVE: "test"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Jobs are separate workflows that can run sequentially or in parallel
jobs:
  # Build and test job - performs initial code quality checks, builds and tests the application
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      # Set up Java environment with caching for dependencies
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # Eclipse Temurin distribution of the JDK
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven" # Caches Maven dependencies to speed up workflow

      # Display Maven and Java versions for debugging
      - name: Display Java and Maven versions
        run: |
          java -version
          mvn --version

      # Check code style and potential bugs
      - name: Check code quality
        run: mvn checkstyle:check spotbugs:check

      # Run unit and integration tests
      - name: Run tests
        run: mvn test verify

      # Package the application and generate JaCoCo coverage report
      - name: Package and generate coverage
        run: mvn package jacoco:report

      # Save test results as artifacts
      - name: Save test results
        uses: actions/upload-artifact@v4
        if: always() # Always upload test results even if tests fail
        with:
          name: test-results
          path: target/surefire-reports/

      # Save JaCoCo coverage reports
      - name: Save coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: target/site/jacoco/

      # Save build artifacts
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-package
          path: target/*.jar

  # Code quality analysis job using SonarQube/SonarCloud
  code-quality:
    name: Code Quality Analysis
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      # Download test results from previous job
      - name: Download test and coverage results
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: target/site/jacoco/

      # SonarCloud analysis - only runs when secrets are available
      - name: SonarCloud Analysis
        if: github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
          -Dsonar.organization=${{ github.repository_owner }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.java.coveragePlugin=jacoco

  # Security scan job to check for vulnerabilities
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      # OWASP dependency check to scan for vulnerabilities in dependencies
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Spring-Application"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
          args: >
            --enableExperimental
            --suppression dependency-check-suppression.xml

      # Upload vulnerability report
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/

  # Docker build and push job - only runs on main branch
  docker-build:
    name: Build and Push Docker Image
    needs: [build-and-test, code-quality, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the built JAR file from build-and-test job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: application-package
          path: target/

      # Login to GitHub Container Registry
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Deploy to development environment (only on main branch)
  deploy-dev:
    name: Deploy to Development
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: development

    steps:
      - name: Deploy to Dev Environment
        run: |
          echo "Deploying to development environment"
          # Add deployment script here - could be kubectl, helm, etc.
          # For example:
          # kubectl apply -f k8s/deployment.yaml

  # Deploy to staging/QA (manual approval required)
  deploy-staging:
    name: Deploy to Staging
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - name: Deploy to Staging Environment
        run: |
          echo "Deploying to staging environment"
          # Add your staging deployment script here

  # Release job - creates GitHub release (only on tag)
  release:
    name: Create Release
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: application-package
          path: ./

      # Generate changelog from commits since last release
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      # Create GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
