name: Terraform CI/CD Pipeline

# Trigger workflow on push to main branch, pull requests, or manual trigger
on:
  push:
    branches: [main]
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-ci.yml"
    # Only run when Terraform files change to avoid unnecessary workflow runs
  pull_request:
    branches: [main]
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-ci.yml"
  # Allow manual trigger of the workflow
  workflow_dispatch:

# Environment variables used throughout the workflow
env:
  # Used for tagging resources in cloud providers
  TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
  # Log level for Terraform operations
  TF_LOG: INFO
  # Working directory for Terraform files
  TERRAFORM_DIRECTORY: ./terraform

# Define jobs for each stage of the CI/CD pipeline
jobs:
  # Format and validate Terraform code
  format-and-validate:
    name: Format and Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Checkout the repository to access Terraform files

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          # Specify a fixed version for consistent builds
          # Avoids unexpected changes due to version updates
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          # Token for Terraform Cloud if using it (optional)

      - name: Terraform Format Check
        id: fmt
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform fmt -check -recursive
        # Ensures consistent code formatting
        # Fails if code is not properly formatted

      - name: Terraform Init
        id: init
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend=false
        # Initialize Terraform without remote backend
        # Needed for validation but not applying changes

      - name: Terraform Validate
        id: validate
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform validate
        # Checks for syntax errors and inconsistencies
        # Verifies if the configuration is internally consistent

  # Lint Terraform code with tflint
  lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    needs: format-and-validate
    # Run after basic format and validation checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1
          # Specify a fixed version for consistent linting

      - name: Initialize TFLint
        run: |
          cd $TERRAFORM_DIRECTORY
          tflint --init
          # Initialize TFLint with plugins specified in .tflint.hcl

      - name: Run TFLint
        run: |
          cd $TERRAFORM_DIRECTORY
          tflint --format=compact
          # Lint Terraform code for potential errors, best practices, etc.

  # Scan for security vulnerabilities with tfsec
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: format-and-validate
    # Run in parallel with linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.TERRAFORM_DIRECTORY }}
          # Identify potential security issues in Terraform code
          # Checks for misconfigurations that could lead to security vulnerabilities

      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.TERRAFORM_DIRECTORY }}
          # Additional security scanner that checks for compliance issues
          # Useful for checking against CIS benchmarks and other standards

  # Run cost estimation for infrastructure changes
  cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    # Run after linting and security scanning
    # Only on PRs to avoid unnecessary cost calculations
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          # API key for Infracost service to estimate cloud costs

      - name: Generate Infracost plan
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend=false
          terraform plan -out=tfplan.binary
          # Create a plan file for Infracost to analyze

      - name: Generate Infracost analysis
        run: |
          cd $TERRAFORM_DIRECTORY
          infracost breakdown --path=tfplan.binary --format=json --out-file=/tmp/infracost.json
          # Generate cost estimate based on the plan

      - name: Post Infracost comment
        uses: infracost/actions/comment@v2
        with:
          path: /tmp/infracost.json
          # Post cost estimation as a comment on the PR
          # Helps visualize the cost impact of changes

  # Plan changes for each environment
  plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    # Run after linting and security scanning
    # Create plans for each environment
    strategy:
      matrix:
        environment: [dev, staging, prod]
        # Define environments to plan for
        # Each might have different variable files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          # AWS credentials for terraform operations
          # Adjust region as needed

      - name: Terraform Init
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend-config=environments/${{ matrix.environment }}/backend.tfvars
          # Initialize Terraform with environment-specific backend config

      - name: Terraform Plan
        id: plan
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform plan -var-file=environments/${{ matrix.environment }}/terraform.tfvars -out=tfplan_${{ matrix.environment }}
          # Create a plan file for each environment
          # Uses environment-specific variables

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: ${{ env.TERRAFORM_DIRECTORY }}/tfplan_${{ matrix.environment }}
          # Save plan as artifact for review or apply job

  # Apply changes to production environment
  apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: plan
    # Run after planning
    # Only apply to production when pushing to main
    if: github.ref == 'refs/heads/main'
    environment: production
    # Requires approval before applying changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan-prod
          path: ${{ env.TERRAFORM_DIRECTORY }}
          # Get the plan file from previous job

      - name: Terraform Init
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend-config=environments/prod/backend.tfvars
          # Initialize Terraform with production backend config

      - name: Terraform Apply
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform apply -auto-approve tfplan_prod
          # Apply the plan to production
          # Auto-approve since approval happens at environment level

  # Document infrastructure changes
  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    # Run after linting and security scanning
    # Generate documentation for the infrastructure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Setup terraform-docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ${{ env.TERRAFORM_DIRECTORY }}
          output-file: README.md
          output-method: inject
          git-push: "true"
          # Generate or update documentation from Terraform code
          # Updates README.md with module documentation

      - name: Generate Terraform Graph
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend=false
          terraform graph | dot -Tsvg > graph.svg
          # Generate a visual representation of the Terraform graph
          # Helps visualize resource dependencies

      - name: Upload Graph
        uses: actions/upload-artifact@v3
        with:
          name: terraform-graph
          path: ${{ env.TERRAFORM_DIRECTORY }}/graph.svg
          # Save graph as artifact for review

  # Drift detection - check if infrastructure matches configuration
  drift-detection:
    name: Drift Detection
    runs-on: ubuntu-latest
    # Run on a schedule, not on every push
    # This job should be in a separate workflow file that runs on a schedule
    # Included here for completeness
    if: github.event_name == 'workflow_dispatch'
    # Only run when manually triggered
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform Init
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform init -backend-config=environments/prod/backend.tfvars
          # Initialize Terraform with production backend config

      - name: Check for Drift
        id: drift
        run: |
          cd $TERRAFORM_DIRECTORY
          terraform plan -detailed-exitcode
          # Exit code 0: No changes
          # Exit code 1: Error
          # Exit code 2: Changes present (drift detected)
        continue-on-error: true
        # Allow the job to continue even if drift is detected

      - name: Report Drift
        if: steps.drift.outputs.exitcode == 2
        run: |
          echo "Drift detected in Terraform configuration"
          # Could send notification to Slack, email, etc.
          # Helps identify when infrastructure has been changed outside of Terraform
